<?php
/**
 * @file
 * Inserts into all your pages a lightbox style login form.
 */

/**
 * Return the rendered Login-box HTML box.
 */
function loginbox() {
  $form = drupal_get_form('user_login_block');
  return theme('loginbox', $form);
}

/**
 * Implementation of hook_init().
 */
function loginbox_init() {
  global $user;

  if ($user->uid < 1) {
    loginbox_add_assets();
  }
}

/**
 * Implementation of hook_theme().
 */
function loginbox_theme() {
  return array(
    'loginbox' => array('content' => NULL),
  );
}

/**
 * Render Login-box box into it's own HTML.
 */
function theme_loginbox($content) {
  return '<div id="loginbox">' . $content . '</div>';
}

/**
 * Add Login-box external files.
 */
function loginbox_add_assets() {
  $path = drupal_get_path('module', 'loginbox');

  // Login-box required assets.
  drupal_add_css($path . '/css/loginbox.css');
  drupal_add_js($path . '/js/loginbox.js');

  // Login-box default theme.
  drupal_add_css($path . '/css/loginbox.default.css');
  drupal_add_js($path . '/js/loginbox.default.js');

  // Login-box overlay.
  drupal_add_css($path . '/css/loginbox.overlay.css');
  drupal_add_js($path . '/js/loginbox.overlay.js');

  // Login-box close button.
  drupal_add_js($path . '/js/loginbox.close.js');
}

/**
 * Implementation of hook_preprocess_page().
 */
function loginbox_preprocess_page(&$vars) {
  $vars['closure'] .= loginbox();
}
