<?php
/**
 * @file
 * Inserts into all your pages a lightbox style login form.
 */

/**
 * Return the rendered Login-box HTML box.
 */
function loginbox() {
  $form = drupal_get_form('user_login_block');
  return theme('loginbox', $form);
}

/**
 * Implementation of hook_theme().
 */
function loginbox_theme() {
  return array(
    'loginbox' => array('content' => NULL),
  );
}

/**
 * Render Login-box box into it's own HTML.
 */
function theme_loginbox($content) {
  return '<div id="loginbox">' . $content . '</div>';
}

/**
 * Implementation of hook_preprocess_page().
 */
function loginbox_preprocess_page(&$vars) {
  $vars['closure'] .= loginbox();
}
