<?php
/**
 * @file
 * Inserts into all your pages a lightbox style login form.
 */

/**
 * Return the rendered Login-box HTML box.
 */
function loginbox() {
  $form = drupal_get_form('loginbox_user_login');
  return theme('loginbox', $form);
}

/**
 * Implementation of hook_init().
 */
function loginbox_init() {
  global $user;

  if ($user->uid < 1) {
    loginbox_add_assets();
  }
}

/**
 * Implementation of hook_theme().
 */
function loginbox_theme() {
  return array(
    'loginbox' => array('content' => NULL),
  );
}

/**
 * Return the user login form.
 */
function loginbox_user_login() {
  $form = user_login_block();

  $form['#validate'][] = 'loginbox_user_login_ajax_validate';

  array_unshift($form['#submit'], 'loginbox_user_login_submit');

  return $form;
}

/**
 * Returns an ajax response to user login validation errrors.
 */
function loginbox_user_login_ajax_validate($form, &$form_state) {
  $errors = form_set_error();
  if (!empty($errors) && loginbox_is_ajax_request()) {
    drupal_get_messages(NULL, TRUE);
    drupal_json(array('errors' => $errors));
    exit;
  }
}

/**
 * Reponse to user login form.
 */
function loginbox_user_login_submit($form, &$form_state) {
  global $user;

  if ($user->uid && loginbox_is_ajax_request()) {
    $destination = drupal_get_destination();
    $destination = str_replace('destination=', '', $destination);
    $destination = urldecode($destination);

    drupal_json(array('destination' => $destination));
    exit;
  }

  // Call default user login submit.
  return user_login_submit($form, &$form_state);
}

/**
 * Check if this is a ajax request.
 *
 * @return
 *   TRUE if it's an ajax request. FALSE if not.
 */
function loginbox_is_ajax_request() {
  return (isset($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest');
}

/**
 * Render Login-box box into it's own HTML.
 */
function theme_loginbox($content) {
  return '<div id="loginbox">' . $content . '</div>';
}

/**
 * Add Login-box external files.
 */
function loginbox_add_assets() {
  $path = drupal_get_path('module', 'loginbox');

  drupal_add_js('misc/jquery.form.js');

  // Login-box required assets.
  drupal_add_css($path . '/css/loginbox.css');
  drupal_add_js($path . '/js/loginbox.js');

  // Login-box default theme.
  drupal_add_css($path . '/css/loginbox.default.css');
  drupal_add_js($path . '/js/loginbox.default.js');

  // Login-box overlay.
  drupal_add_css($path . '/css/loginbox.overlay.css');
  drupal_add_js($path . '/js/loginbox.overlay.js');

  // Login-box close button.
  drupal_add_js($path . '/js/loginbox.close.js');
}

/**
 * Implementation of hook_preprocess_page().
 */
function loginbox_preprocess_page(&$vars) {
  $vars['closure'] .= loginbox();
}
